# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Thomas R. Koll
email: tomk32@gmail.com
description: Ruby on Rails developer available for projects remotely and in Austria
keywords: Ruby on Rails,Ruby,Javascript,developer,freelancer,linz,austria,germany,hacker
motto: just a geek trying to change the world
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tomk32.github.io" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  presentations:
    output: true

profile_image: /assets/tomk32.jpg
profile_image_small: /assets/tomk32_small.jpg
external_profiles:
  github: http://github.com/TomK32
  stackoverflow: http://stackoverflow.com/users/story/336392
  linkedin: https://www.linkedin.com/in/thomas-r-koll-78150775/
  thingiverse: http://www.thingiverse.com/TomK32
  twitter: http://twitter.com/TomK32

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  style: compressed
gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - config.ru
  - vendor
  - Procfile
  - Rakefile

theme: jekyll-theme-minimal
tag_page_layout: tag_page
tag_page_dir: tag


# The Reveal theme
reveal_theme: black.css
reveal_transition: default
reveal_theme_path: /reveal.js/css/theme/
reveal_notes_server: false
# Additional reveal.js options
reveal_options:
# Additional reveal.js dependencies
reveal_dependencies:
reveal_path: /reveal.js/

